version: 2
updates:
  - package-ecosystem: "github"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      
