language: node_js
node_js:
  - 'v16.0.0'
branches:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  verbose: true
  keep_history: true
  name: dengxiaoning
  email: d1236688@163.com
  on:
    branch: main
